"use client";

import styles from "./hero.module.css";
import { Button } from "@/components/ui/Button";
import Image from "next/image";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function Hero() {
     const { status } = useSession();
    const buildResumeHref = status === "authenticated"
      ? "/editor/new"
      : `/auth/login?callbackUrl=${encodeURIComponent("/editor/new")}`;

    return (
        <section className={styles.hero}>
            <div className={styles.hero__container}>
                <div className={styles.hero__content}>
                    <h1 className={styles.hero__title}>Build your dream career with <span className={styles.hero__title__highlighted}>AI-powered</span> resumes</h1>
                    <p className={styles.hero__description}>Land more interviews with a professional, ATS-optimized resume generated by the world&apos;s most advanced AI writing assistant.</p>

                    <div className={styles.hero__buttons}>
                        <Link href={buildResumeHref}>
                            <Button variant="primary">Build My Resume Now</Button>
                        </Link>
                        
                        <Link href="/templates">
                            <Button variant="outline">View Templates</Button>
                        </Link>
                        
                    </div>

                </div>

                <div className={styles.hero__image_container}>
                    <Image 
                    src="/hero_image1.png" 
                    alt="App Dashboard Preview" 
                    width={1200}
                    height={600}
                    className={styles.heroImage}
                    priority
                />
                </div>

                
            </div>

            <div className={styles.trusted_by}>
                    <p>TRUSTED BY PROFESSIONALS</p>
            </div>
        </section>
    )
}
