import styles from "./hero.module.css";
import { Button } from "@/components/ui/Button";
import Image from "next/image";

export default function Hero() {
    return (
        <section className={styles.hero}>
            <div className={styles.hero__container}>
                <div className={styles.hero__content}>
                    <h1 className={styles.hero__title}>Build your dream career with <span className={styles.hero__title__highlighted}>AI-powered</span> resumes</h1>
                    <p className={styles.hero__description}>Land more interviews with a professional, ATS-optimized resume generated by the world's most advanced AI writing assistant.</p>

                    <div className={styles.hero__buttons}>
                        <Button variant="primary">Build My Resume Now</Button>
                        <Button variant="outline">View Templates</Button>
                    </div>

                </div>

                <div className={styles.hero__image_container}>
                    <Image 
                    src="/hero_image1.png" 
                    alt="App Dashboard Preview" 
                    width={1200}
                    height={600}
                    className={styles.heroImage}
                    priority
                />
                </div>

                
            </div>

            <div className={styles.trusted_by}>
                    <p>TRUSTED BY PROFESSIONALS</p>
            </div>
        </section>
    )
}